"""Write the drawer gate chain (one Isaac process per piece, sequential on one GPU) from the frozen drawer list.
usage: python tools/l8x_assets/drawer_gate_chain.py LIST.json CODE_DIR GPU OUT_DIR CHAIN.sh"""
from __future__ import annotations

import json
import sys

U = "/data/harvest/assets_x/molmospaces/objects_thor/usd"


def usd_of(piece: str) -> str:
    pkg = "thor_Dresser" if piece.startswith("Dresser") else "thor_Desk" if piece.startswith("Desk") else \
        "thor_" + "_".join(piece.split("_")[:3]) if piece.startswith("Side_Table") else "thor_" + piece
    return f"{U}/{pkg}/{piece}/{piece}.usda"


def main(argv=None):
    a = argv or sys.argv[1:]
    lst = json.load(open(a[0]))
    code, gpu, out, chain = a[1], a[2], a[3], a[4]
    by = {}
    for s, t in sorted(lst["gate"].items()):
        by.setdefault(t.split("__", 1)[1], []).append((t, s))  # one (piece, handle) per process
    lines = ["#!/bin/bash", "# L8X-assets drawer gate chain (generated by drawer_gate_chain.py)",
             "I=/data/harvest/code_l8x_assets_dev/tools/l8x_assets/isaac.sh  # LF copy (the archived one can be CRLF)"]
    for k, (ph, ts) in enumerate(sorted(by.items())):
        piece = ph.split("__")[0]
        tasks = ",".join(t for t, _ in ts)
        seeds = ",".join(s for _, s in ts)
        lines.append(f"bash $I {code} {gpu} xn_dr{k} tools.l8x_assets.gate_drawer --piece-usd {usd_of(piece)} "
                     f"--piece {piece} --tasks {tasks} --seeds {seeds} --out {out}")
    lines.append("echo CHAIN_DONE")
    open(chain, "w", newline="\n").write("\n".join(lines) + "\n")
    print(len(by), "pieces ->", chain)


if __name__ == "__main__":
    main()
